// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package databricks

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetCurrentUser(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetCurrentUserResult, error) {
	var rv GetCurrentUserResult
	err := ctx.Invoke("databricks:index/getCurrentUser:getCurrentUser", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getCurrentUser.
type GetCurrentUserResult struct {
	Alphanumeric string `pulumi:"alphanumeric"`
	ExternalId   string `pulumi:"externalId"`
	Home         string `pulumi:"home"`
	// The provider-assigned unique ID for this managed resource.
	Id           string `pulumi:"id"`
	Repos        string `pulumi:"repos"`
	UserName     string `pulumi:"userName"`
	WorkspaceUrl string `pulumi:"workspaceUrl"`
}
