// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package databricks

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupGroup(ctx *pulumi.Context, args *LookupGroupArgs, opts ...pulumi.InvokeOption) (*LookupGroupResult, error) {
	var rv LookupGroupResult
	err := ctx.Invoke("databricks:index/getGroup:getGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getGroup.
type LookupGroupArgs struct {
	AllowClusterCreate      *bool    `pulumi:"allowClusterCreate"`
	AllowInstancePoolCreate *bool    `pulumi:"allowInstancePoolCreate"`
	ChildGroups             []string `pulumi:"childGroups"`
	DatabricksSqlAccess     *bool    `pulumi:"databricksSqlAccess"`
	DisplayName             string   `pulumi:"displayName"`
	ExternalId              *string  `pulumi:"externalId"`
	Groups                  []string `pulumi:"groups"`
	InstanceProfiles        []string `pulumi:"instanceProfiles"`
	// Deprecated: Please use `users`, `service_principals`, and `child_groups` instead
	Members           []string `pulumi:"members"`
	Recursive         *bool    `pulumi:"recursive"`
	ServicePrincipals []string `pulumi:"servicePrincipals"`
	Users             []string `pulumi:"users"`
	WorkspaceAccess   *bool    `pulumi:"workspaceAccess"`
}

// A collection of values returned by getGroup.
type LookupGroupResult struct {
	AllowClusterCreate      *bool    `pulumi:"allowClusterCreate"`
	AllowInstancePoolCreate *bool    `pulumi:"allowInstancePoolCreate"`
	ChildGroups             []string `pulumi:"childGroups"`
	DatabricksSqlAccess     *bool    `pulumi:"databricksSqlAccess"`
	DisplayName             string   `pulumi:"displayName"`
	ExternalId              string   `pulumi:"externalId"`
	Groups                  []string `pulumi:"groups"`
	// The provider-assigned unique ID for this managed resource.
	Id               string   `pulumi:"id"`
	InstanceProfiles []string `pulumi:"instanceProfiles"`
	// Deprecated: Please use `users`, `service_principals`, and `child_groups` instead
	Members           []string `pulumi:"members"`
	Recursive         *bool    `pulumi:"recursive"`
	ServicePrincipals []string `pulumi:"servicePrincipals"`
	Users             []string `pulumi:"users"`
	WorkspaceAccess   *bool    `pulumi:"workspaceAccess"`
}

func LookupGroupOutput(ctx *pulumi.Context, args LookupGroupOutputArgs, opts ...pulumi.InvokeOption) LookupGroupResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupGroupResult, error) {
			args := v.(LookupGroupArgs)
			r, err := LookupGroup(ctx, &args, opts...)
			return *r, err
		}).(LookupGroupResultOutput)
}

// A collection of arguments for invoking getGroup.
type LookupGroupOutputArgs struct {
	AllowClusterCreate      pulumi.BoolPtrInput     `pulumi:"allowClusterCreate"`
	AllowInstancePoolCreate pulumi.BoolPtrInput     `pulumi:"allowInstancePoolCreate"`
	ChildGroups             pulumi.StringArrayInput `pulumi:"childGroups"`
	DatabricksSqlAccess     pulumi.BoolPtrInput     `pulumi:"databricksSqlAccess"`
	DisplayName             pulumi.StringInput      `pulumi:"displayName"`
	ExternalId              pulumi.StringPtrInput   `pulumi:"externalId"`
	Groups                  pulumi.StringArrayInput `pulumi:"groups"`
	InstanceProfiles        pulumi.StringArrayInput `pulumi:"instanceProfiles"`
	// Deprecated: Please use `users`, `service_principals`, and `child_groups` instead
	Members           pulumi.StringArrayInput `pulumi:"members"`
	Recursive         pulumi.BoolPtrInput     `pulumi:"recursive"`
	ServicePrincipals pulumi.StringArrayInput `pulumi:"servicePrincipals"`
	Users             pulumi.StringArrayInput `pulumi:"users"`
	WorkspaceAccess   pulumi.BoolPtrInput     `pulumi:"workspaceAccess"`
}

func (LookupGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupGroupArgs)(nil)).Elem()
}

// A collection of values returned by getGroup.
type LookupGroupResultOutput struct{ *pulumi.OutputState }

func (LookupGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupGroupResult)(nil)).Elem()
}

func (o LookupGroupResultOutput) ToLookupGroupResultOutput() LookupGroupResultOutput {
	return o
}

func (o LookupGroupResultOutput) ToLookupGroupResultOutputWithContext(ctx context.Context) LookupGroupResultOutput {
	return o
}

func (o LookupGroupResultOutput) AllowClusterCreate() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupGroupResult) *bool { return v.AllowClusterCreate }).(pulumi.BoolPtrOutput)
}

func (o LookupGroupResultOutput) AllowInstancePoolCreate() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupGroupResult) *bool { return v.AllowInstancePoolCreate }).(pulumi.BoolPtrOutput)
}

func (o LookupGroupResultOutput) ChildGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupGroupResult) []string { return v.ChildGroups }).(pulumi.StringArrayOutput)
}

func (o LookupGroupResultOutput) DatabricksSqlAccess() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupGroupResult) *bool { return v.DatabricksSqlAccess }).(pulumi.BoolPtrOutput)
}

func (o LookupGroupResultOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGroupResult) string { return v.DisplayName }).(pulumi.StringOutput)
}

func (o LookupGroupResultOutput) ExternalId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGroupResult) string { return v.ExternalId }).(pulumi.StringOutput)
}

func (o LookupGroupResultOutput) Groups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupGroupResult) []string { return v.Groups }).(pulumi.StringArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupGroupResultOutput) InstanceProfiles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupGroupResult) []string { return v.InstanceProfiles }).(pulumi.StringArrayOutput)
}

// Deprecated: Please use `users`, `service_principals`, and `child_groups` instead
func (o LookupGroupResultOutput) Members() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupGroupResult) []string { return v.Members }).(pulumi.StringArrayOutput)
}

func (o LookupGroupResultOutput) Recursive() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupGroupResult) *bool { return v.Recursive }).(pulumi.BoolPtrOutput)
}

func (o LookupGroupResultOutput) ServicePrincipals() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupGroupResult) []string { return v.ServicePrincipals }).(pulumi.StringArrayOutput)
}

func (o LookupGroupResultOutput) Users() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupGroupResult) []string { return v.Users }).(pulumi.StringArrayOutput)
}

func (o LookupGroupResultOutput) WorkspaceAccess() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupGroupResult) *bool { return v.WorkspaceAccess }).(pulumi.BoolPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupGroupResultOutput{})
}
