// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package databricks

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetServicePrincipals(ctx *pulumi.Context, args *GetServicePrincipalsArgs, opts ...pulumi.InvokeOption) (*GetServicePrincipalsResult, error) {
	var rv GetServicePrincipalsResult
	err := ctx.Invoke("databricks:index/getServicePrincipals:getServicePrincipals", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getServicePrincipals.
type GetServicePrincipalsArgs struct {
	ApplicationIds      []string `pulumi:"applicationIds"`
	DisplayNameContains *string  `pulumi:"displayNameContains"`
}

// A collection of values returned by getServicePrincipals.
type GetServicePrincipalsResult struct {
	ApplicationIds      []string `pulumi:"applicationIds"`
	DisplayNameContains string   `pulumi:"displayNameContains"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
}

func GetServicePrincipalsOutput(ctx *pulumi.Context, args GetServicePrincipalsOutputArgs, opts ...pulumi.InvokeOption) GetServicePrincipalsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetServicePrincipalsResult, error) {
			args := v.(GetServicePrincipalsArgs)
			r, err := GetServicePrincipals(ctx, &args, opts...)
			return *r, err
		}).(GetServicePrincipalsResultOutput)
}

// A collection of arguments for invoking getServicePrincipals.
type GetServicePrincipalsOutputArgs struct {
	ApplicationIds      pulumi.StringArrayInput `pulumi:"applicationIds"`
	DisplayNameContains pulumi.StringPtrInput   `pulumi:"displayNameContains"`
}

func (GetServicePrincipalsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServicePrincipalsArgs)(nil)).Elem()
}

// A collection of values returned by getServicePrincipals.
type GetServicePrincipalsResultOutput struct{ *pulumi.OutputState }

func (GetServicePrincipalsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServicePrincipalsResult)(nil)).Elem()
}

func (o GetServicePrincipalsResultOutput) ToGetServicePrincipalsResultOutput() GetServicePrincipalsResultOutput {
	return o
}

func (o GetServicePrincipalsResultOutput) ToGetServicePrincipalsResultOutputWithContext(ctx context.Context) GetServicePrincipalsResultOutput {
	return o
}

func (o GetServicePrincipalsResultOutput) ApplicationIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetServicePrincipalsResult) []string { return v.ApplicationIds }).(pulumi.StringArrayOutput)
}

func (o GetServicePrincipalsResultOutput) DisplayNameContains() pulumi.StringOutput {
	return o.ApplyT(func(v GetServicePrincipalsResult) string { return v.DisplayNameContains }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetServicePrincipalsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetServicePrincipalsResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetServicePrincipalsResultOutput{})
}
