// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package databricks

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetSqlWarehouse(ctx *pulumi.Context, args *GetSqlWarehouseArgs, opts ...pulumi.InvokeOption) (*GetSqlWarehouseResult, error) {
	var rv GetSqlWarehouseResult
	err := ctx.Invoke("databricks:index/getSqlWarehouse:getSqlWarehouse", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSqlWarehouse.
type GetSqlWarehouseArgs struct {
	AutoStopMins            *int                       `pulumi:"autoStopMins"`
	Channel                 *GetSqlWarehouseChannel    `pulumi:"channel"`
	ClusterSize             *string                    `pulumi:"clusterSize"`
	DataSourceId            *string                    `pulumi:"dataSourceId"`
	EnablePhoton            *bool                      `pulumi:"enablePhoton"`
	EnableServerlessCompute *bool                      `pulumi:"enableServerlessCompute"`
	Id                      string                     `pulumi:"id"`
	InstanceProfileArn      *string                    `pulumi:"instanceProfileArn"`
	JdbcUrl                 *string                    `pulumi:"jdbcUrl"`
	MaxNumClusters          *int                       `pulumi:"maxNumClusters"`
	MinNumClusters          *int                       `pulumi:"minNumClusters"`
	Name                    *string                    `pulumi:"name"`
	NumClusters             *int                       `pulumi:"numClusters"`
	OdbcParams              *GetSqlWarehouseOdbcParams `pulumi:"odbcParams"`
	SpotInstancePolicy      *string                    `pulumi:"spotInstancePolicy"`
	State                   *string                    `pulumi:"state"`
	Tags                    *GetSqlWarehouseTags       `pulumi:"tags"`
}

// A collection of values returned by getSqlWarehouse.
type GetSqlWarehouseResult struct {
	AutoStopMins            int                       `pulumi:"autoStopMins"`
	Channel                 GetSqlWarehouseChannel    `pulumi:"channel"`
	ClusterSize             string                    `pulumi:"clusterSize"`
	DataSourceId            string                    `pulumi:"dataSourceId"`
	EnablePhoton            bool                      `pulumi:"enablePhoton"`
	EnableServerlessCompute bool                      `pulumi:"enableServerlessCompute"`
	Id                      string                    `pulumi:"id"`
	InstanceProfileArn      string                    `pulumi:"instanceProfileArn"`
	JdbcUrl                 string                    `pulumi:"jdbcUrl"`
	MaxNumClusters          int                       `pulumi:"maxNumClusters"`
	MinNumClusters          int                       `pulumi:"minNumClusters"`
	Name                    string                    `pulumi:"name"`
	NumClusters             int                       `pulumi:"numClusters"`
	OdbcParams              GetSqlWarehouseOdbcParams `pulumi:"odbcParams"`
	SpotInstancePolicy      string                    `pulumi:"spotInstancePolicy"`
	State                   string                    `pulumi:"state"`
	Tags                    GetSqlWarehouseTags       `pulumi:"tags"`
}

func GetSqlWarehouseOutput(ctx *pulumi.Context, args GetSqlWarehouseOutputArgs, opts ...pulumi.InvokeOption) GetSqlWarehouseResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetSqlWarehouseResult, error) {
			args := v.(GetSqlWarehouseArgs)
			r, err := GetSqlWarehouse(ctx, &args, opts...)
			return *r, err
		}).(GetSqlWarehouseResultOutput)
}

// A collection of arguments for invoking getSqlWarehouse.
type GetSqlWarehouseOutputArgs struct {
	AutoStopMins            pulumi.IntPtrInput                `pulumi:"autoStopMins"`
	Channel                 GetSqlWarehouseChannelPtrInput    `pulumi:"channel"`
	ClusterSize             pulumi.StringPtrInput             `pulumi:"clusterSize"`
	DataSourceId            pulumi.StringPtrInput             `pulumi:"dataSourceId"`
	EnablePhoton            pulumi.BoolPtrInput               `pulumi:"enablePhoton"`
	EnableServerlessCompute pulumi.BoolPtrInput               `pulumi:"enableServerlessCompute"`
	Id                      pulumi.StringInput                `pulumi:"id"`
	InstanceProfileArn      pulumi.StringPtrInput             `pulumi:"instanceProfileArn"`
	JdbcUrl                 pulumi.StringPtrInput             `pulumi:"jdbcUrl"`
	MaxNumClusters          pulumi.IntPtrInput                `pulumi:"maxNumClusters"`
	MinNumClusters          pulumi.IntPtrInput                `pulumi:"minNumClusters"`
	Name                    pulumi.StringPtrInput             `pulumi:"name"`
	NumClusters             pulumi.IntPtrInput                `pulumi:"numClusters"`
	OdbcParams              GetSqlWarehouseOdbcParamsPtrInput `pulumi:"odbcParams"`
	SpotInstancePolicy      pulumi.StringPtrInput             `pulumi:"spotInstancePolicy"`
	State                   pulumi.StringPtrInput             `pulumi:"state"`
	Tags                    GetSqlWarehouseTagsPtrInput       `pulumi:"tags"`
}

func (GetSqlWarehouseOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSqlWarehouseArgs)(nil)).Elem()
}

// A collection of values returned by getSqlWarehouse.
type GetSqlWarehouseResultOutput struct{ *pulumi.OutputState }

func (GetSqlWarehouseResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSqlWarehouseResult)(nil)).Elem()
}

func (o GetSqlWarehouseResultOutput) ToGetSqlWarehouseResultOutput() GetSqlWarehouseResultOutput {
	return o
}

func (o GetSqlWarehouseResultOutput) ToGetSqlWarehouseResultOutputWithContext(ctx context.Context) GetSqlWarehouseResultOutput {
	return o
}

func (o GetSqlWarehouseResultOutput) AutoStopMins() pulumi.IntOutput {
	return o.ApplyT(func(v GetSqlWarehouseResult) int { return v.AutoStopMins }).(pulumi.IntOutput)
}

func (o GetSqlWarehouseResultOutput) Channel() GetSqlWarehouseChannelOutput {
	return o.ApplyT(func(v GetSqlWarehouseResult) GetSqlWarehouseChannel { return v.Channel }).(GetSqlWarehouseChannelOutput)
}

func (o GetSqlWarehouseResultOutput) ClusterSize() pulumi.StringOutput {
	return o.ApplyT(func(v GetSqlWarehouseResult) string { return v.ClusterSize }).(pulumi.StringOutput)
}

func (o GetSqlWarehouseResultOutput) DataSourceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetSqlWarehouseResult) string { return v.DataSourceId }).(pulumi.StringOutput)
}

func (o GetSqlWarehouseResultOutput) EnablePhoton() pulumi.BoolOutput {
	return o.ApplyT(func(v GetSqlWarehouseResult) bool { return v.EnablePhoton }).(pulumi.BoolOutput)
}

func (o GetSqlWarehouseResultOutput) EnableServerlessCompute() pulumi.BoolOutput {
	return o.ApplyT(func(v GetSqlWarehouseResult) bool { return v.EnableServerlessCompute }).(pulumi.BoolOutput)
}

func (o GetSqlWarehouseResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetSqlWarehouseResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetSqlWarehouseResultOutput) InstanceProfileArn() pulumi.StringOutput {
	return o.ApplyT(func(v GetSqlWarehouseResult) string { return v.InstanceProfileArn }).(pulumi.StringOutput)
}

func (o GetSqlWarehouseResultOutput) JdbcUrl() pulumi.StringOutput {
	return o.ApplyT(func(v GetSqlWarehouseResult) string { return v.JdbcUrl }).(pulumi.StringOutput)
}

func (o GetSqlWarehouseResultOutput) MaxNumClusters() pulumi.IntOutput {
	return o.ApplyT(func(v GetSqlWarehouseResult) int { return v.MaxNumClusters }).(pulumi.IntOutput)
}

func (o GetSqlWarehouseResultOutput) MinNumClusters() pulumi.IntOutput {
	return o.ApplyT(func(v GetSqlWarehouseResult) int { return v.MinNumClusters }).(pulumi.IntOutput)
}

func (o GetSqlWarehouseResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetSqlWarehouseResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetSqlWarehouseResultOutput) NumClusters() pulumi.IntOutput {
	return o.ApplyT(func(v GetSqlWarehouseResult) int { return v.NumClusters }).(pulumi.IntOutput)
}

func (o GetSqlWarehouseResultOutput) OdbcParams() GetSqlWarehouseOdbcParamsOutput {
	return o.ApplyT(func(v GetSqlWarehouseResult) GetSqlWarehouseOdbcParams { return v.OdbcParams }).(GetSqlWarehouseOdbcParamsOutput)
}

func (o GetSqlWarehouseResultOutput) SpotInstancePolicy() pulumi.StringOutput {
	return o.ApplyT(func(v GetSqlWarehouseResult) string { return v.SpotInstancePolicy }).(pulumi.StringOutput)
}

func (o GetSqlWarehouseResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v GetSqlWarehouseResult) string { return v.State }).(pulumi.StringOutput)
}

func (o GetSqlWarehouseResultOutput) Tags() GetSqlWarehouseTagsOutput {
	return o.ApplyT(func(v GetSqlWarehouseResult) GetSqlWarehouseTags { return v.Tags }).(GetSqlWarehouseTagsOutput)
}

func init() {
	pulumi.RegisterOutputType(GetSqlWarehouseResultOutput{})
}
