// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks
{
    [DatabricksResourceType("databricks:index/cluster:Cluster")]
    public partial class Cluster : Pulumi.CustomResource
    {
        [Output("autoscale")]
        public Output<Outputs.ClusterAutoscale?> Autoscale { get; private set; } = null!;

        [Output("autoterminationMinutes")]
        public Output<int?> AutoterminationMinutes { get; private set; } = null!;

        [Output("awsAttributes")]
        public Output<Outputs.ClusterAwsAttributes?> AwsAttributes { get; private set; } = null!;

        [Output("azureAttributes")]
        public Output<Outputs.ClusterAzureAttributes?> AzureAttributes { get; private set; } = null!;

        [Output("clusterId")]
        public Output<string> ClusterId { get; private set; } = null!;

        [Output("clusterLogConf")]
        public Output<Outputs.ClusterClusterLogConf?> ClusterLogConf { get; private set; } = null!;

        [Output("clusterName")]
        public Output<string?> ClusterName { get; private set; } = null!;

        [Output("customTags")]
        public Output<ImmutableDictionary<string, object>?> CustomTags { get; private set; } = null!;

        [Output("dataSecurityMode")]
        public Output<string?> DataSecurityMode { get; private set; } = null!;

        [Output("defaultTags")]
        public Output<ImmutableDictionary<string, object>> DefaultTags { get; private set; } = null!;

        [Output("dockerImage")]
        public Output<Outputs.ClusterDockerImage?> DockerImage { get; private set; } = null!;

        [Output("driverInstancePoolId")]
        public Output<string> DriverInstancePoolId { get; private set; } = null!;

        [Output("driverNodeTypeId")]
        public Output<string> DriverNodeTypeId { get; private set; } = null!;

        [Output("enableElasticDisk")]
        public Output<bool> EnableElasticDisk { get; private set; } = null!;

        [Output("enableLocalDiskEncryption")]
        public Output<bool> EnableLocalDiskEncryption { get; private set; } = null!;

        [Output("gcpAttributes")]
        public Output<Outputs.ClusterGcpAttributes?> GcpAttributes { get; private set; } = null!;

        [Output("idempotencyToken")]
        public Output<string?> IdempotencyToken { get; private set; } = null!;

        [Output("initScripts")]
        public Output<ImmutableArray<Outputs.ClusterInitScript>> InitScripts { get; private set; } = null!;

        [Output("instancePoolId")]
        public Output<string?> InstancePoolId { get; private set; } = null!;

        [Output("isPinned")]
        public Output<bool?> IsPinned { get; private set; } = null!;

        [Output("libraries")]
        public Output<ImmutableArray<Outputs.ClusterLibrary>> Libraries { get; private set; } = null!;

        [Output("nodeTypeId")]
        public Output<string> NodeTypeId { get; private set; } = null!;

        [Output("numWorkers")]
        public Output<int?> NumWorkers { get; private set; } = null!;

        [Output("policyId")]
        public Output<string?> PolicyId { get; private set; } = null!;

        [Output("singleUserName")]
        public Output<string?> SingleUserName { get; private set; } = null!;

        [Output("sparkConf")]
        public Output<ImmutableDictionary<string, object>?> SparkConf { get; private set; } = null!;

        [Output("sparkEnvVars")]
        public Output<ImmutableDictionary<string, object>?> SparkEnvVars { get; private set; } = null!;

        [Output("sparkVersion")]
        public Output<string> SparkVersion { get; private set; } = null!;

        [Output("sshPublicKeys")]
        public Output<ImmutableArray<string>> SshPublicKeys { get; private set; } = null!;

        [Output("state")]
        public Output<string> State { get; private set; } = null!;

        [Output("url")]
        public Output<string> Url { get; private set; } = null!;

        [Output("workloadType")]
        public Output<Outputs.ClusterWorkloadType?> WorkloadType { get; private set; } = null!;


        /// <summary>
        /// Create a Cluster resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Cluster(string name, ClusterArgs args, CustomResourceOptions? options = null)
            : base("databricks:index/cluster:Cluster", name, args ?? new ClusterArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Cluster(string name, Input<string> id, ClusterState? state = null, CustomResourceOptions? options = null)
            : base("databricks:index/cluster:Cluster", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Cluster resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Cluster Get(string name, Input<string> id, ClusterState? state = null, CustomResourceOptions? options = null)
        {
            return new Cluster(name, id, state, options);
        }
    }

    public sealed class ClusterArgs : Pulumi.ResourceArgs
    {
        [Input("autoscale")]
        public Input<Inputs.ClusterAutoscaleArgs>? Autoscale { get; set; }

        [Input("autoterminationMinutes")]
        public Input<int>? AutoterminationMinutes { get; set; }

        [Input("awsAttributes")]
        public Input<Inputs.ClusterAwsAttributesArgs>? AwsAttributes { get; set; }

        [Input("azureAttributes")]
        public Input<Inputs.ClusterAzureAttributesArgs>? AzureAttributes { get; set; }

        [Input("clusterId")]
        public Input<string>? ClusterId { get; set; }

        [Input("clusterLogConf")]
        public Input<Inputs.ClusterClusterLogConfArgs>? ClusterLogConf { get; set; }

        [Input("clusterName")]
        public Input<string>? ClusterName { get; set; }

        [Input("customTags")]
        private InputMap<object>? _customTags;
        public InputMap<object> CustomTags
        {
            get => _customTags ?? (_customTags = new InputMap<object>());
            set => _customTags = value;
        }

        [Input("dataSecurityMode")]
        public Input<string>? DataSecurityMode { get; set; }

        [Input("dockerImage")]
        public Input<Inputs.ClusterDockerImageArgs>? DockerImage { get; set; }

        [Input("driverInstancePoolId")]
        public Input<string>? DriverInstancePoolId { get; set; }

        [Input("driverNodeTypeId")]
        public Input<string>? DriverNodeTypeId { get; set; }

        [Input("enableElasticDisk")]
        public Input<bool>? EnableElasticDisk { get; set; }

        [Input("enableLocalDiskEncryption")]
        public Input<bool>? EnableLocalDiskEncryption { get; set; }

        [Input("gcpAttributes")]
        public Input<Inputs.ClusterGcpAttributesArgs>? GcpAttributes { get; set; }

        [Input("idempotencyToken")]
        public Input<string>? IdempotencyToken { get; set; }

        [Input("initScripts")]
        private InputList<Inputs.ClusterInitScriptArgs>? _initScripts;
        public InputList<Inputs.ClusterInitScriptArgs> InitScripts
        {
            get => _initScripts ?? (_initScripts = new InputList<Inputs.ClusterInitScriptArgs>());
            set => _initScripts = value;
        }

        [Input("instancePoolId")]
        public Input<string>? InstancePoolId { get; set; }

        [Input("isPinned")]
        public Input<bool>? IsPinned { get; set; }

        [Input("libraries")]
        private InputList<Inputs.ClusterLibraryArgs>? _libraries;
        public InputList<Inputs.ClusterLibraryArgs> Libraries
        {
            get => _libraries ?? (_libraries = new InputList<Inputs.ClusterLibraryArgs>());
            set => _libraries = value;
        }

        [Input("nodeTypeId")]
        public Input<string>? NodeTypeId { get; set; }

        [Input("numWorkers")]
        public Input<int>? NumWorkers { get; set; }

        [Input("policyId")]
        public Input<string>? PolicyId { get; set; }

        [Input("singleUserName")]
        public Input<string>? SingleUserName { get; set; }

        [Input("sparkConf")]
        private InputMap<object>? _sparkConf;
        public InputMap<object> SparkConf
        {
            get => _sparkConf ?? (_sparkConf = new InputMap<object>());
            set => _sparkConf = value;
        }

        [Input("sparkEnvVars")]
        private InputMap<object>? _sparkEnvVars;
        public InputMap<object> SparkEnvVars
        {
            get => _sparkEnvVars ?? (_sparkEnvVars = new InputMap<object>());
            set => _sparkEnvVars = value;
        }

        [Input("sparkVersion", required: true)]
        public Input<string> SparkVersion { get; set; } = null!;

        [Input("sshPublicKeys")]
        private InputList<string>? _sshPublicKeys;
        public InputList<string> SshPublicKeys
        {
            get => _sshPublicKeys ?? (_sshPublicKeys = new InputList<string>());
            set => _sshPublicKeys = value;
        }

        [Input("workloadType")]
        public Input<Inputs.ClusterWorkloadTypeArgs>? WorkloadType { get; set; }

        public ClusterArgs()
        {
        }
    }

    public sealed class ClusterState : Pulumi.ResourceArgs
    {
        [Input("autoscale")]
        public Input<Inputs.ClusterAutoscaleGetArgs>? Autoscale { get; set; }

        [Input("autoterminationMinutes")]
        public Input<int>? AutoterminationMinutes { get; set; }

        [Input("awsAttributes")]
        public Input<Inputs.ClusterAwsAttributesGetArgs>? AwsAttributes { get; set; }

        [Input("azureAttributes")]
        public Input<Inputs.ClusterAzureAttributesGetArgs>? AzureAttributes { get; set; }

        [Input("clusterId")]
        public Input<string>? ClusterId { get; set; }

        [Input("clusterLogConf")]
        public Input<Inputs.ClusterClusterLogConfGetArgs>? ClusterLogConf { get; set; }

        [Input("clusterName")]
        public Input<string>? ClusterName { get; set; }

        [Input("customTags")]
        private InputMap<object>? _customTags;
        public InputMap<object> CustomTags
        {
            get => _customTags ?? (_customTags = new InputMap<object>());
            set => _customTags = value;
        }

        [Input("dataSecurityMode")]
        public Input<string>? DataSecurityMode { get; set; }

        [Input("defaultTags")]
        private InputMap<object>? _defaultTags;
        public InputMap<object> DefaultTags
        {
            get => _defaultTags ?? (_defaultTags = new InputMap<object>());
            set => _defaultTags = value;
        }

        [Input("dockerImage")]
        public Input<Inputs.ClusterDockerImageGetArgs>? DockerImage { get; set; }

        [Input("driverInstancePoolId")]
        public Input<string>? DriverInstancePoolId { get; set; }

        [Input("driverNodeTypeId")]
        public Input<string>? DriverNodeTypeId { get; set; }

        [Input("enableElasticDisk")]
        public Input<bool>? EnableElasticDisk { get; set; }

        [Input("enableLocalDiskEncryption")]
        public Input<bool>? EnableLocalDiskEncryption { get; set; }

        [Input("gcpAttributes")]
        public Input<Inputs.ClusterGcpAttributesGetArgs>? GcpAttributes { get; set; }

        [Input("idempotencyToken")]
        public Input<string>? IdempotencyToken { get; set; }

        [Input("initScripts")]
        private InputList<Inputs.ClusterInitScriptGetArgs>? _initScripts;
        public InputList<Inputs.ClusterInitScriptGetArgs> InitScripts
        {
            get => _initScripts ?? (_initScripts = new InputList<Inputs.ClusterInitScriptGetArgs>());
            set => _initScripts = value;
        }

        [Input("instancePoolId")]
        public Input<string>? InstancePoolId { get; set; }

        [Input("isPinned")]
        public Input<bool>? IsPinned { get; set; }

        [Input("libraries")]
        private InputList<Inputs.ClusterLibraryGetArgs>? _libraries;
        public InputList<Inputs.ClusterLibraryGetArgs> Libraries
        {
            get => _libraries ?? (_libraries = new InputList<Inputs.ClusterLibraryGetArgs>());
            set => _libraries = value;
        }

        [Input("nodeTypeId")]
        public Input<string>? NodeTypeId { get; set; }

        [Input("numWorkers")]
        public Input<int>? NumWorkers { get; set; }

        [Input("policyId")]
        public Input<string>? PolicyId { get; set; }

        [Input("singleUserName")]
        public Input<string>? SingleUserName { get; set; }

        [Input("sparkConf")]
        private InputMap<object>? _sparkConf;
        public InputMap<object> SparkConf
        {
            get => _sparkConf ?? (_sparkConf = new InputMap<object>());
            set => _sparkConf = value;
        }

        [Input("sparkEnvVars")]
        private InputMap<object>? _sparkEnvVars;
        public InputMap<object> SparkEnvVars
        {
            get => _sparkEnvVars ?? (_sparkEnvVars = new InputMap<object>());
            set => _sparkEnvVars = value;
        }

        [Input("sparkVersion")]
        public Input<string>? SparkVersion { get; set; }

        [Input("sshPublicKeys")]
        private InputList<string>? _sshPublicKeys;
        public InputList<string> SshPublicKeys
        {
            get => _sshPublicKeys ?? (_sshPublicKeys = new InputList<string>());
            set => _sshPublicKeys = value;
        }

        [Input("state")]
        public Input<string>? State { get; set; }

        [Input("url")]
        public Input<string>? Url { get; set; }

        [Input("workloadType")]
        public Input<Inputs.ClusterWorkloadTypeGetArgs>? WorkloadType { get; set; }

        public ClusterState()
        {
        }
    }
}
