// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks
{
    public static class GetAwsCrossaccountPolicy
    {
        public static Task<GetAwsCrossaccountPolicyResult> InvokeAsync(GetAwsCrossaccountPolicyArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetAwsCrossaccountPolicyResult>("databricks:index/getAwsCrossaccountPolicy:getAwsCrossaccountPolicy", args ?? new GetAwsCrossaccountPolicyArgs(), options.WithDefaults());

        public static Output<GetAwsCrossaccountPolicyResult> Invoke(GetAwsCrossaccountPolicyInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetAwsCrossaccountPolicyResult>("databricks:index/getAwsCrossaccountPolicy:getAwsCrossaccountPolicy", args ?? new GetAwsCrossaccountPolicyInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAwsCrossaccountPolicyArgs : Pulumi.InvokeArgs
    {
        [Input("passRoles")]
        private List<string>? _passRoles;
        public List<string> PassRoles
        {
            get => _passRoles ?? (_passRoles = new List<string>());
            set => _passRoles = value;
        }

        public GetAwsCrossaccountPolicyArgs()
        {
        }
    }

    public sealed class GetAwsCrossaccountPolicyInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("passRoles")]
        private InputList<string>? _passRoles;
        public InputList<string> PassRoles
        {
            get => _passRoles ?? (_passRoles = new InputList<string>());
            set => _passRoles = value;
        }

        public GetAwsCrossaccountPolicyInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetAwsCrossaccountPolicyResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Json;
        public readonly ImmutableArray<string> PassRoles;

        [OutputConstructor]
        private GetAwsCrossaccountPolicyResult(
            string id,

            string json,

            ImmutableArray<string> passRoles)
        {
            Id = id;
            Json = json;
            PassRoles = passRoles;
        }
    }
}
