// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks
{
    public static class GetCurrentUser
    {
        public static Task<GetCurrentUserResult> InvokeAsync(InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetCurrentUserResult>("databricks:index/getCurrentUser:getCurrentUser", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetCurrentUserResult
    {
        public readonly string Alphanumeric;
        public readonly string ExternalId;
        public readonly string Home;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Repos;
        public readonly string UserName;
        public readonly string WorkspaceUrl;

        [OutputConstructor]
        private GetCurrentUserResult(
            string alphanumeric,

            string externalId,

            string home,

            string id,

            string repos,

            string userName,

            string workspaceUrl)
        {
            Alphanumeric = alphanumeric;
            ExternalId = externalId;
            Home = home;
            Id = id;
            Repos = repos;
            UserName = userName;
            WorkspaceUrl = workspaceUrl;
        }
    }
}
