// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks
{
    public static class GetNodeType
    {
        public static Task<GetNodeTypeResult> InvokeAsync(GetNodeTypeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetNodeTypeResult>("databricks:index/getNodeType:getNodeType", args ?? new GetNodeTypeArgs(), options.WithDefaults());

        public static Output<GetNodeTypeResult> Invoke(GetNodeTypeInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetNodeTypeResult>("databricks:index/getNodeType:getNodeType", args ?? new GetNodeTypeInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNodeTypeArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// Node category, which can be one of (depending on the cloud environment, could be checked with `databricks clusters list-node-types|jq '.node_types[]|.category'|sort |uniq`):
        /// * `General Purpose` (all clouds)
        /// * `General Purpose (HDD)` (Azure)
        /// * `Compute Optimized` (all clouds)
        /// * `Memory Optimized` (all clouds)
        /// * `Memory Optimized (Remote HDD)` (Azure)
        /// * `Storage Optimized` (AWS, Azure)
        /// * `GPU Accelerated` (AWS, Azure)
        /// </summary>
        [Input("category")]
        public string? Category { get; set; }

        /// <summary>
        /// Number of gigabytes per core available on instance. Conflicts with `min_memory_gb`. Defaults to *0*.
        /// </summary>
        [Input("gbPerCore")]
        public int? GbPerCore { get; set; }

        /// <summary>
        /// if we should limit the search only to nodes with AWS Graviton CPUs. Default to *false*.
        /// </summary>
        [Input("graviton")]
        public bool? Graviton { get; set; }

        /// <summary>
        /// . Pick only nodes that have IO Cache. Defaults to *false*.
        /// </summary>
        [Input("isIoCacheEnabled")]
        public bool? IsIoCacheEnabled { get; set; }

        /// <summary>
        /// Pick only nodes with local storage. Defaults to *false*.
        /// </summary>
        [Input("localDisk")]
        public bool? LocalDisk { get; set; }

        /// <summary>
        /// Minimum number of CPU cores available on instance. Defaults to *0*.
        /// </summary>
        [Input("minCores")]
        public int? MinCores { get; set; }

        /// <summary>
        /// Minimum number of GPU's attached to instance. Defaults to *0*.
        /// </summary>
        [Input("minGpus")]
        public int? MinGpus { get; set; }

        /// <summary>
        /// Minimum amount of memory per node in gigabytes. Defaults to *0*.
        /// </summary>
        [Input("minMemoryGb")]
        public int? MinMemoryGb { get; set; }

        /// <summary>
        /// Pick only nodes that can run Photon driver. Defaults to *false*.
        /// </summary>
        [Input("photonDriverCapable")]
        public bool? PhotonDriverCapable { get; set; }

        /// <summary>
        /// Pick only nodes that can run Photon workers. Defaults to *false*.
        /// </summary>
        [Input("photonWorkerCapable")]
        public bool? PhotonWorkerCapable { get; set; }

        /// <summary>
        /// Pick only nodes that support port forwarding. Defaults to *false*.
        /// </summary>
        [Input("supportPortForwarding")]
        public bool? SupportPortForwarding { get; set; }

        public GetNodeTypeArgs()
        {
        }
    }

    public sealed class GetNodeTypeInvokeArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// Node category, which can be one of (depending on the cloud environment, could be checked with `databricks clusters list-node-types|jq '.node_types[]|.category'|sort |uniq`):
        /// * `General Purpose` (all clouds)
        /// * `General Purpose (HDD)` (Azure)
        /// * `Compute Optimized` (all clouds)
        /// * `Memory Optimized` (all clouds)
        /// * `Memory Optimized (Remote HDD)` (Azure)
        /// * `Storage Optimized` (AWS, Azure)
        /// * `GPU Accelerated` (AWS, Azure)
        /// </summary>
        [Input("category")]
        public Input<string>? Category { get; set; }

        /// <summary>
        /// Number of gigabytes per core available on instance. Conflicts with `min_memory_gb`. Defaults to *0*.
        /// </summary>
        [Input("gbPerCore")]
        public Input<int>? GbPerCore { get; set; }

        /// <summary>
        /// if we should limit the search only to nodes with AWS Graviton CPUs. Default to *false*.
        /// </summary>
        [Input("graviton")]
        public Input<bool>? Graviton { get; set; }

        /// <summary>
        /// . Pick only nodes that have IO Cache. Defaults to *false*.
        /// </summary>
        [Input("isIoCacheEnabled")]
        public Input<bool>? IsIoCacheEnabled { get; set; }

        /// <summary>
        /// Pick only nodes with local storage. Defaults to *false*.
        /// </summary>
        [Input("localDisk")]
        public Input<bool>? LocalDisk { get; set; }

        /// <summary>
        /// Minimum number of CPU cores available on instance. Defaults to *0*.
        /// </summary>
        [Input("minCores")]
        public Input<int>? MinCores { get; set; }

        /// <summary>
        /// Minimum number of GPU's attached to instance. Defaults to *0*.
        /// </summary>
        [Input("minGpus")]
        public Input<int>? MinGpus { get; set; }

        /// <summary>
        /// Minimum amount of memory per node in gigabytes. Defaults to *0*.
        /// </summary>
        [Input("minMemoryGb")]
        public Input<int>? MinMemoryGb { get; set; }

        /// <summary>
        /// Pick only nodes that can run Photon driver. Defaults to *false*.
        /// </summary>
        [Input("photonDriverCapable")]
        public Input<bool>? PhotonDriverCapable { get; set; }

        /// <summary>
        /// Pick only nodes that can run Photon workers. Defaults to *false*.
        /// </summary>
        [Input("photonWorkerCapable")]
        public Input<bool>? PhotonWorkerCapable { get; set; }

        /// <summary>
        /// Pick only nodes that support port forwarding. Defaults to *false*.
        /// </summary>
        [Input("supportPortForwarding")]
        public Input<bool>? SupportPortForwarding { get; set; }

        public GetNodeTypeInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetNodeTypeResult
    {
        public readonly string? Category;
        public readonly int? GbPerCore;
        public readonly bool? Graviton;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly bool? IsIoCacheEnabled;
        public readonly bool? LocalDisk;
        public readonly int? MinCores;
        public readonly int? MinGpus;
        public readonly int? MinMemoryGb;
        public readonly bool? PhotonDriverCapable;
        public readonly bool? PhotonWorkerCapable;
        public readonly bool? SupportPortForwarding;

        [OutputConstructor]
        private GetNodeTypeResult(
            string? category,

            int? gbPerCore,

            bool? graviton,

            string id,

            bool? isIoCacheEnabled,

            bool? localDisk,

            int? minCores,

            int? minGpus,

            int? minMemoryGb,

            bool? photonDriverCapable,

            bool? photonWorkerCapable,

            bool? supportPortForwarding)
        {
            Category = category;
            GbPerCore = gbPerCore;
            Graviton = graviton;
            Id = id;
            IsIoCacheEnabled = isIoCacheEnabled;
            LocalDisk = localDisk;
            MinCores = minCores;
            MinGpus = minGpus;
            MinMemoryGb = minMemoryGb;
            PhotonDriverCapable = photonDriverCapable;
            PhotonWorkerCapable = photonWorkerCapable;
            SupportPortForwarding = supportPortForwarding;
        }
    }
}
