// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks
{
    public static class GetSqlWarehouses
    {
        public static Task<GetSqlWarehousesResult> InvokeAsync(GetSqlWarehousesArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetSqlWarehousesResult>("databricks:index/getSqlWarehouses:getSqlWarehouses", args ?? new GetSqlWarehousesArgs(), options.WithDefaults());

        public static Output<GetSqlWarehousesResult> Invoke(GetSqlWarehousesInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetSqlWarehousesResult>("databricks:index/getSqlWarehouses:getSqlWarehouses", args ?? new GetSqlWarehousesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSqlWarehousesArgs : Pulumi.InvokeArgs
    {
        [Input("ids")]
        private List<string>? _ids;
        public List<string> Ids
        {
            get => _ids ?? (_ids = new List<string>());
            set => _ids = value;
        }

        [Input("warehouseNameContains")]
        public string? WarehouseNameContains { get; set; }

        public GetSqlWarehousesArgs()
        {
        }
    }

    public sealed class GetSqlWarehousesInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("ids")]
        private InputList<string>? _ids;
        public InputList<string> Ids
        {
            get => _ids ?? (_ids = new InputList<string>());
            set => _ids = value;
        }

        [Input("warehouseNameContains")]
        public Input<string>? WarehouseNameContains { get; set; }

        public GetSqlWarehousesInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetSqlWarehousesResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> Ids;
        public readonly string? WarehouseNameContains;

        [OutputConstructor]
        private GetSqlWarehousesResult(
            string id,

            ImmutableArray<string> ids,

            string? warehouseNameContains)
        {
            Id = id;
            Ids = ids;
            WarehouseNameContains = warehouseNameContains;
        }
    }
}
