// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks
{
    [DatabricksResourceType("databricks:index/pipeline:Pipeline")]
    public partial class Pipeline : Pulumi.CustomResource
    {
        [Output("allowDuplicateNames")]
        public Output<bool?> AllowDuplicateNames { get; private set; } = null!;

        [Output("channel")]
        public Output<string?> Channel { get; private set; } = null!;

        [Output("clusters")]
        public Output<ImmutableArray<Outputs.PipelineCluster>> Clusters { get; private set; } = null!;

        [Output("configuration")]
        public Output<ImmutableDictionary<string, object>?> Configuration { get; private set; } = null!;

        [Output("continuous")]
        public Output<bool?> Continuous { get; private set; } = null!;

        [Output("development")]
        public Output<bool?> Development { get; private set; } = null!;

        [Output("edition")]
        public Output<string?> Edition { get; private set; } = null!;

        [Output("filters")]
        public Output<Outputs.PipelineFilters?> Filters { get; private set; } = null!;

        [Output("id")]
        public Output<string> Id { get; private set; } = null!;

        [Output("libraries")]
        public Output<ImmutableArray<Outputs.PipelineLibrary>> Libraries { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("photon")]
        public Output<bool?> Photon { get; private set; } = null!;

        [Output("storage")]
        public Output<string?> Storage { get; private set; } = null!;

        [Output("target")]
        public Output<string?> Target { get; private set; } = null!;

        [Output("url")]
        public Output<string> Url { get; private set; } = null!;


        /// <summary>
        /// Create a Pipeline resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Pipeline(string name, PipelineArgs? args = null, CustomResourceOptions? options = null)
            : base("databricks:index/pipeline:Pipeline", name, args ?? new PipelineArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Pipeline(string name, Input<string> id, PipelineState? state = null, CustomResourceOptions? options = null)
            : base("databricks:index/pipeline:Pipeline", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Pipeline resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Pipeline Get(string name, Input<string> id, PipelineState? state = null, CustomResourceOptions? options = null)
        {
            return new Pipeline(name, id, state, options);
        }
    }

    public sealed class PipelineArgs : Pulumi.ResourceArgs
    {
        [Input("allowDuplicateNames")]
        public Input<bool>? AllowDuplicateNames { get; set; }

        [Input("channel")]
        public Input<string>? Channel { get; set; }

        [Input("clusters")]
        private InputList<Inputs.PipelineClusterArgs>? _clusters;
        public InputList<Inputs.PipelineClusterArgs> Clusters
        {
            get => _clusters ?? (_clusters = new InputList<Inputs.PipelineClusterArgs>());
            set => _clusters = value;
        }

        [Input("configuration")]
        private InputMap<object>? _configuration;
        public InputMap<object> Configuration
        {
            get => _configuration ?? (_configuration = new InputMap<object>());
            set => _configuration = value;
        }

        [Input("continuous")]
        public Input<bool>? Continuous { get; set; }

        [Input("development")]
        public Input<bool>? Development { get; set; }

        [Input("edition")]
        public Input<string>? Edition { get; set; }

        [Input("filters")]
        public Input<Inputs.PipelineFiltersArgs>? Filters { get; set; }

        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("libraries")]
        private InputList<Inputs.PipelineLibraryArgs>? _libraries;
        public InputList<Inputs.PipelineLibraryArgs> Libraries
        {
            get => _libraries ?? (_libraries = new InputList<Inputs.PipelineLibraryArgs>());
            set => _libraries = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("photon")]
        public Input<bool>? Photon { get; set; }

        [Input("storage")]
        public Input<string>? Storage { get; set; }

        [Input("target")]
        public Input<string>? Target { get; set; }

        public PipelineArgs()
        {
        }
    }

    public sealed class PipelineState : Pulumi.ResourceArgs
    {
        [Input("allowDuplicateNames")]
        public Input<bool>? AllowDuplicateNames { get; set; }

        [Input("channel")]
        public Input<string>? Channel { get; set; }

        [Input("clusters")]
        private InputList<Inputs.PipelineClusterGetArgs>? _clusters;
        public InputList<Inputs.PipelineClusterGetArgs> Clusters
        {
            get => _clusters ?? (_clusters = new InputList<Inputs.PipelineClusterGetArgs>());
            set => _clusters = value;
        }

        [Input("configuration")]
        private InputMap<object>? _configuration;
        public InputMap<object> Configuration
        {
            get => _configuration ?? (_configuration = new InputMap<object>());
            set => _configuration = value;
        }

        [Input("continuous")]
        public Input<bool>? Continuous { get; set; }

        [Input("development")]
        public Input<bool>? Development { get; set; }

        [Input("edition")]
        public Input<string>? Edition { get; set; }

        [Input("filters")]
        public Input<Inputs.PipelineFiltersGetArgs>? Filters { get; set; }

        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("libraries")]
        private InputList<Inputs.PipelineLibraryGetArgs>? _libraries;
        public InputList<Inputs.PipelineLibraryGetArgs> Libraries
        {
            get => _libraries ?? (_libraries = new InputList<Inputs.PipelineLibraryGetArgs>());
            set => _libraries = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("photon")]
        public Input<bool>? Photon { get; set; }

        [Input("storage")]
        public Input<string>? Storage { get; set; }

        [Input("target")]
        public Input<string>? Target { get; set; }

        [Input("url")]
        public Input<string>? Url { get; set; }

        public PipelineState()
        {
        }
    }
}
