# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('databricks')


class _ExportableConfig(types.ModuleType):
    @property
    def account_id(self) -> Optional[str]:
        return __config__.get('accountId') or _utilities.get_env('DATABRICKS_ACCOUNT_ID')

    @property
    def auth_type(self) -> Optional[str]:
        return __config__.get('authType')

    @property
    def azure_client_id(self) -> Optional[str]:
        return __config__.get('azureClientId')

    @property
    def azure_client_secret(self) -> Optional[str]:
        return __config__.get('azureClientSecret')

    @property
    def azure_environment(self) -> Optional[str]:
        return __config__.get('azureEnvironment')

    @property
    def azure_tenant_id(self) -> Optional[str]:
        return __config__.get('azureTenantId')

    @property
    def azure_use_msi(self) -> Optional[bool]:
        return __config__.get_bool('azureUseMsi')

    @property
    def azure_workspace_resource_id(self) -> Optional[str]:
        return __config__.get('azureWorkspaceResourceId')

    @property
    def config_file(self) -> Optional[str]:
        return __config__.get('configFile') or _utilities.get_env('DATABRICKS_CONFIG_FILE')

    @property
    def debug_headers(self) -> Optional[bool]:
        return __config__.get_bool('debugHeaders') or _utilities.get_env_bool('DATABRICKS_DEBUG_HEADERS')

    @property
    def debug_truncate_bytes(self) -> Optional[int]:
        return __config__.get_int('debugTruncateBytes') or _utilities.get_env_int('DATABRICKS_DEBUG_TRUNCATE_BYTES')

    @property
    def google_credentials(self) -> Optional[str]:
        return __config__.get('googleCredentials')

    @property
    def google_service_account(self) -> Optional[str]:
        return __config__.get('googleServiceAccount')

    @property
    def host(self) -> Optional[str]:
        return __config__.get('host') or _utilities.get_env('DATABRICKS_HOST')

    @property
    def http_timeout_seconds(self) -> Optional[int]:
        return __config__.get_int('httpTimeoutSeconds')

    @property
    def password(self) -> Optional[str]:
        return __config__.get('password') or _utilities.get_env('DATABRICKS_PASSWORD')

    @property
    def profile(self) -> Optional[str]:
        return __config__.get('profile') or _utilities.get_env('DATABRICKS_PROFILE')

    @property
    def rate_limit(self) -> Optional[int]:
        return __config__.get_int('rateLimit') or _utilities.get_env_int('DATABRICKS_RATE_LIMIT')

    @property
    def skip_verify(self) -> Optional[bool]:
        return __config__.get_bool('skipVerify')

    @property
    def token(self) -> Optional[str]:
        return __config__.get('token') or _utilities.get_env('DATABRICKS_TOKEN')

    @property
    def username(self) -> Optional[str]:
        return __config__.get('username') or _utilities.get_env('DATABRICKS_USERNAME')

