// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks.Inputs
{

    public sealed class GetClusterClusterInfoInputArgs : Pulumi.ResourceArgs
    {
        [Input("autoscale")]
        public Input<Inputs.GetClusterClusterInfoAutoscaleInputArgs>? Autoscale { get; set; }

        [Input("autoterminationMinutes")]
        public Input<int>? AutoterminationMinutes { get; set; }

        [Input("awsAttributes")]
        public Input<Inputs.GetClusterClusterInfoAwsAttributesInputArgs>? AwsAttributes { get; set; }

        [Input("azureAttributes")]
        public Input<Inputs.GetClusterClusterInfoAzureAttributesInputArgs>? AzureAttributes { get; set; }

        [Input("clusterCores")]
        public Input<double>? ClusterCores { get; set; }

        [Input("clusterId")]
        public Input<string>? ClusterId { get; set; }

        [Input("clusterLogConf")]
        public Input<Inputs.GetClusterClusterInfoClusterLogConfInputArgs>? ClusterLogConf { get; set; }

        [Input("clusterLogStatus")]
        public Input<Inputs.GetClusterClusterInfoClusterLogStatusInputArgs>? ClusterLogStatus { get; set; }

        [Input("clusterMemoryMb")]
        public Input<int>? ClusterMemoryMb { get; set; }

        [Input("clusterName")]
        public Input<string>? ClusterName { get; set; }

        [Input("clusterSource")]
        public Input<string>? ClusterSource { get; set; }

        [Input("creatorUserName")]
        public Input<string>? CreatorUserName { get; set; }

        [Input("customTags")]
        private InputMap<object>? _customTags;
        public InputMap<object> CustomTags
        {
            get => _customTags ?? (_customTags = new InputMap<object>());
            set => _customTags = value;
        }

        [Input("dataSecurityMode")]
        public Input<string>? DataSecurityMode { get; set; }

        [Input("defaultTags", required: true)]
        private InputMap<object>? _defaultTags;
        public InputMap<object> DefaultTags
        {
            get => _defaultTags ?? (_defaultTags = new InputMap<object>());
            set => _defaultTags = value;
        }

        [Input("dockerImage")]
        public Input<Inputs.GetClusterClusterInfoDockerImageInputArgs>? DockerImage { get; set; }

        [Input("driver")]
        public Input<Inputs.GetClusterClusterInfoDriverInputArgs>? Driver { get; set; }

        [Input("driverInstancePoolId", required: true)]
        public Input<string> DriverInstancePoolId { get; set; } = null!;

        [Input("driverNodeTypeId")]
        public Input<string>? DriverNodeTypeId { get; set; }

        [Input("enableElasticDisk")]
        public Input<bool>? EnableElasticDisk { get; set; }

        [Input("enableLocalDiskEncryption")]
        public Input<bool>? EnableLocalDiskEncryption { get; set; }

        [Input("executors")]
        private InputList<Inputs.GetClusterClusterInfoExecutorInputArgs>? _executors;
        public InputList<Inputs.GetClusterClusterInfoExecutorInputArgs> Executors
        {
            get => _executors ?? (_executors = new InputList<Inputs.GetClusterClusterInfoExecutorInputArgs>());
            set => _executors = value;
        }

        [Input("gcpAttributes")]
        public Input<Inputs.GetClusterClusterInfoGcpAttributesInputArgs>? GcpAttributes { get; set; }

        [Input("initScripts")]
        private InputList<Inputs.GetClusterClusterInfoInitScriptInputArgs>? _initScripts;
        public InputList<Inputs.GetClusterClusterInfoInitScriptInputArgs> InitScripts
        {
            get => _initScripts ?? (_initScripts = new InputList<Inputs.GetClusterClusterInfoInitScriptInputArgs>());
            set => _initScripts = value;
        }

        [Input("instancePoolId")]
        public Input<string>? InstancePoolId { get; set; }

        [Input("jdbcPort")]
        public Input<int>? JdbcPort { get; set; }

        [Input("lastActivityTime")]
        public Input<int>? LastActivityTime { get; set; }

        [Input("lastStateLossTime")]
        public Input<int>? LastStateLossTime { get; set; }

        [Input("nodeTypeId")]
        public Input<string>? NodeTypeId { get; set; }

        [Input("numWorkers")]
        public Input<int>? NumWorkers { get; set; }

        [Input("policyId")]
        public Input<string>? PolicyId { get; set; }

        [Input("singleUserName")]
        public Input<string>? SingleUserName { get; set; }

        [Input("sparkConf")]
        private InputMap<object>? _sparkConf;
        public InputMap<object> SparkConf
        {
            get => _sparkConf ?? (_sparkConf = new InputMap<object>());
            set => _sparkConf = value;
        }

        [Input("sparkContextId")]
        public Input<int>? SparkContextId { get; set; }

        [Input("sparkEnvVars")]
        private InputMap<object>? _sparkEnvVars;
        public InputMap<object> SparkEnvVars
        {
            get => _sparkEnvVars ?? (_sparkEnvVars = new InputMap<object>());
            set => _sparkEnvVars = value;
        }

        [Input("sparkVersion", required: true)]
        public Input<string> SparkVersion { get; set; } = null!;

        [Input("sshPublicKeys")]
        private InputList<string>? _sshPublicKeys;
        public InputList<string> SshPublicKeys
        {
            get => _sshPublicKeys ?? (_sshPublicKeys = new InputList<string>());
            set => _sshPublicKeys = value;
        }

        [Input("startTime")]
        public Input<int>? StartTime { get; set; }

        [Input("state", required: true)]
        public Input<string> State { get; set; } = null!;

        [Input("stateMessage")]
        public Input<string>? StateMessage { get; set; }

        [Input("terminateTime")]
        public Input<int>? TerminateTime { get; set; }

        [Input("terminationReason")]
        public Input<Inputs.GetClusterClusterInfoTerminationReasonInputArgs>? TerminationReason { get; set; }

        public GetClusterClusterInfoInputArgs()
        {
        }
    }
}
