// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Databricks.Inputs
{

    public sealed class MlflowWebhookJobSpecArgs : Pulumi.ResourceArgs
    {
        [Input("accessToken", required: true)]
        public Input<string> AccessToken { get; set; } = null!;

        [Input("jobId", required: true)]
        public Input<string> JobId { get; set; } = null!;

        [Input("workspaceUrl")]
        public Input<string>? WorkspaceUrl { get; set; }

        public MlflowWebhookJobSpecArgs()
        {
        }
    }
}
