// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getAwsCrossaccountPolicy(args?: GetAwsCrossaccountPolicyArgs, opts?: pulumi.InvokeOptions): Promise<GetAwsCrossaccountPolicyResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("databricks:index/getAwsCrossaccountPolicy:getAwsCrossaccountPolicy", {
        "passRoles": args.passRoles,
    }, opts);
}

/**
 * A collection of arguments for invoking getAwsCrossaccountPolicy.
 */
export interface GetAwsCrossaccountPolicyArgs {
    passRoles?: string[];
}

/**
 * A collection of values returned by getAwsCrossaccountPolicy.
 */
export interface GetAwsCrossaccountPolicyResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly json: string;
    readonly passRoles?: string[];
}

export function getAwsCrossaccountPolicyOutput(args?: GetAwsCrossaccountPolicyOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAwsCrossaccountPolicyResult> {
    return pulumi.output(args).apply(a => getAwsCrossaccountPolicy(a, opts))
}

/**
 * A collection of arguments for invoking getAwsCrossaccountPolicy.
 */
export interface GetAwsCrossaccountPolicyOutputArgs {
    passRoles?: pulumi.Input<pulumi.Input<string>[]>;
}
