// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export function getSqlWarehouse(args: GetSqlWarehouseArgs, opts?: pulumi.InvokeOptions): Promise<GetSqlWarehouseResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("databricks:index/getSqlWarehouse:getSqlWarehouse", {
        "autoStopMins": args.autoStopMins,
        "channel": args.channel,
        "clusterSize": args.clusterSize,
        "dataSourceId": args.dataSourceId,
        "enablePhoton": args.enablePhoton,
        "enableServerlessCompute": args.enableServerlessCompute,
        "id": args.id,
        "instanceProfileArn": args.instanceProfileArn,
        "jdbcUrl": args.jdbcUrl,
        "maxNumClusters": args.maxNumClusters,
        "minNumClusters": args.minNumClusters,
        "name": args.name,
        "numClusters": args.numClusters,
        "odbcParams": args.odbcParams,
        "spotInstancePolicy": args.spotInstancePolicy,
        "state": args.state,
        "tags": args.tags,
    }, opts);
}

/**
 * A collection of arguments for invoking getSqlWarehouse.
 */
export interface GetSqlWarehouseArgs {
    autoStopMins?: number;
    channel?: inputs.GetSqlWarehouseChannel;
    clusterSize?: string;
    dataSourceId?: string;
    enablePhoton?: boolean;
    enableServerlessCompute?: boolean;
    id: string;
    instanceProfileArn?: string;
    jdbcUrl?: string;
    maxNumClusters?: number;
    minNumClusters?: number;
    name?: string;
    numClusters?: number;
    odbcParams?: inputs.GetSqlWarehouseOdbcParams;
    spotInstancePolicy?: string;
    state?: string;
    tags?: inputs.GetSqlWarehouseTags;
}

/**
 * A collection of values returned by getSqlWarehouse.
 */
export interface GetSqlWarehouseResult {
    readonly autoStopMins: number;
    readonly channel: outputs.GetSqlWarehouseChannel;
    readonly clusterSize: string;
    readonly dataSourceId: string;
    readonly enablePhoton: boolean;
    readonly enableServerlessCompute: boolean;
    readonly id: string;
    readonly instanceProfileArn: string;
    readonly jdbcUrl: string;
    readonly maxNumClusters: number;
    readonly minNumClusters: number;
    readonly name: string;
    readonly numClusters: number;
    readonly odbcParams: outputs.GetSqlWarehouseOdbcParams;
    readonly spotInstancePolicy: string;
    readonly state: string;
    readonly tags: outputs.GetSqlWarehouseTags;
}

export function getSqlWarehouseOutput(args: GetSqlWarehouseOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSqlWarehouseResult> {
    return pulumi.output(args).apply(a => getSqlWarehouse(a, opts))
}

/**
 * A collection of arguments for invoking getSqlWarehouse.
 */
export interface GetSqlWarehouseOutputArgs {
    autoStopMins?: pulumi.Input<number>;
    channel?: pulumi.Input<inputs.GetSqlWarehouseChannelArgs>;
    clusterSize?: pulumi.Input<string>;
    dataSourceId?: pulumi.Input<string>;
    enablePhoton?: pulumi.Input<boolean>;
    enableServerlessCompute?: pulumi.Input<boolean>;
    id: pulumi.Input<string>;
    instanceProfileArn?: pulumi.Input<string>;
    jdbcUrl?: pulumi.Input<string>;
    maxNumClusters?: pulumi.Input<number>;
    minNumClusters?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    numClusters?: pulumi.Input<number>;
    odbcParams?: pulumi.Input<inputs.GetSqlWarehouseOdbcParamsArgs>;
    spotInstancePolicy?: pulumi.Input<string>;
    state?: pulumi.Input<string>;
    tags?: pulumi.Input<inputs.GetSqlWarehouseTagsArgs>;
}
